#!/bin/bash
cd /samba/bin/default
mkdir objs
ld -o objs/replace.c.3.o -r lib/replace/replace.c.3.o lib/replace/closefrom.c.3.o
cp lib/talloc/talloc.c.2.o objs/
cp lib/util/time_basic.c.1.o objs/
cp lib/util/blocking.c.14.o objs/
cp lib/util/iov_buf.c.24.o objs/
ld -o objs/debug.c.12.o -r lib/util/debug.c.12.o lib/util/gpfswrap.c.11.o lib/util/close_low_fd.c.8.o
ld -o objs/tevent.c.1.o -r lib/tevent/tevent_threads.c.1.o lib/tevent/tevent.c.1.o lib/tevent/tevent_queue.c.1.o lib/tevent/tevent_immediate.c.1.o lib/tevent/tevent_signal.c.1.o lib/tevent/tevent_wrapper.c.1.o lib/tevent/tevent_poll.c.1.o lib/tevent/tevent_util.c.1.o lib/tevent/tevent_wakeup.c.1.o lib/tevent/tevent_standard.c.1.o lib/tevent/tevent_epoll.c.1.o lib/tevent/tevent_timed.c.1.o lib/tevent/tevent_debug.c.1.o lib/tevent/tevent_req.c.1.o lib/tevent/tevent_fd.c.1.o
ld -o objs/sys_rw.c.9.o -r lib/util/sys_rw_data.c.9.o lib/util/sys_rw.c.9.o
cp lib/util/genrand.c.28.o objs/
cp lib/util/setid.c.78.o objs/
ld -o objs/tiniparser.c.5.o -r lib/util/util_str.c.32.o lib/util/fault.c.20.o lib/util/util_file.c.21.o lib/util/signal.c.20.o dynconfig/dynconfig.c.1.o lib/util/pidfile.c.21.o lib/util/util.c.21.o lib/util/unix_match.c.32.o lib/util/system.c.32.o lib/util/util_strlist.c.21.o lib/util/time.c.21.o lib/util/charset/util_unistr_w.c.2.o lib/util/util_id.c.32.o lib/util/server_id.c.32.o lib/util/charset/util_str.c.2.o lib/util/charset/codepoints.c.2.o lib/util/tini.c.3.o lib/util/substitute.c.21.o lib/util/become_daemon.c.21.o lib/util/util_process.c.21.o lib/util/idtree.c.21.o lib/util/memcache.c.32.o lib/util/select.c.21.o lib/util/base64.c.32.o lib/util/charset/pull_push.c.2.o lib/util/fsusage.c.32.o lib/util/idtree_random.c.32.o lib/util/tftw.c.32.o lib/util/data_blob.c.21.o lib/util/bitmap.c.21.o lib/util/rfc1738.c.32.o lib/util/ms_fnmatch.c.32.o lib/util/util_str_hex.c.89.o lib/util/tiniparser.c.5.o lib/util/dprintf.c.32.o lib/util/tfork.c.32.o lib/util/util_paths.c.32.o lib/util/sys_popen.c.21.o lib/util/charset/iconv.c.1.o lib/util/smb_threads.c.32.o lib/util/util_strlist_v3.c.32.o lib/util/strv.c.7.o lib/util/util_str_common.c.32.o lib/util/strv_util.c.21.o lib/crypto/md4.c.2.o lib/util/charset/util_unistr.c.2.o lib/util/charset/convert_string.c.2.o lib/util/charset/charset_macosxfs.c.1.o lib/util/talloc_keep_secret.c.32.o lib/util/genrand_util.c.32.o lib/util/params.c.32.o lib/util/smb_strtox.c.22.o lib/util/tevent_debug.c.32.o lib/util/getpass.c.32.o lib/util/charset/weird.c.1.o lib/util/util_net.c.32.o lib/util/mkdir_p.c.21.o lib/util/rbtree.c.32.o lib/util/talloc_stack.c.32.o
ld -o objs/doserr.c.1.o -r libcli/util/errmap_unix.c.1.o libcli/util/hresult.c.1.o libcli/util/doserr.c.1.o libcli/util/errormap.c.1.o libcli/util/nterr.c.1.o
ld -o objs/ndr_string.c.196.o -r librpc/ndr/uuid.c.196.o librpc/ndr/ndr_misc.c.196.o librpc/ndr/ndr_basic.c.196.o librpc/ndr/util.c.196.o librpc/gen_ndr/ndr_misc.c.196.o librpc/ndr/ndr_string.c.196.o librpc/ndr/ndr.c.196.o
ld -o objs/check.c.1.o -r lib/tdb/common/dump.c.1.o lib/tdb/common/transaction.c.1.o lib/tdb/common/rescue.c.1.o lib/tdb/common/open.c.1.o lib/tdb/common/lock.c.1.o lib/tdb/common/tdb.c.1.o lib/tdb/common/check.c.1.o lib/tdb/common/mutex.c.1.o lib/tdb/common/error.c.1.o lib/tdb/common/freelistcheck.c.1.o lib/tdb/common/traverse.c.1.o lib/tdb/common/summary.c.1.o lib/tdb/common/freelist.c.1.o lib/tdb/common/hash.c.1.o lib/tdb/common/io.c.1.o
ld -o objs/dom_sid.c.1.o -r libcli/security/sddl.c.1.o libcli/security/object_tree.c.1.o libcli/security/secdesc.c.1.o librpc/gen_ndr/ndr_security.c.55.o libcli/security/security_descriptor.c.1.o libcli/security/util_sid.c.1.o libcli/security/secacl.c.1.o libcli/security/session.c.1.o libcli/security/privileges.c.1.o libcli/security/display_sec.c.1.o libcli/security/create_descriptor.c.1.o libcli/security/access_check.c.1.o libcli/security/secace.c.1.o libcli/security/dom_sid.c.1.o librpc/ndr/ndr_sec_helper.c.55.o libcli/security/security_token.c.1.o
ld -o objs/nbtname.c.1.o -r libcli/nbt/nbtname.c.1.o librpc/ndr/ndr_dns_utils.c.8.o librpc/ndr/ndr_nbt.c.137.o librpc/gen_ndr/ndr_dnsp.c.50.o librpc/ndr/ndr_dns.c.8.o librpc/gen_ndr/ndr_nbt.c.137.o librpc/gen_ndr/ndr_dns.c.8.o librpc/ndr/ndr_dnsp.c.50.o
ld -o objs/tevent_unix.c.70.o -r lib/util/tevent_werror.c.70.o lib/util/tevent_req_profile.c.70.o lib/util/tevent_ntstatus.c.70.o lib/util/tevent_unix.c.70.o
cp lib/util/util_tdb.c.68.o objs/
cp lib/tdb_wrap/tdb_wrap.c.1.o objs/
cp lib/param/loadparm_server_role.c.6.o objs/
ld -o objs/ndr_eventlog6.c.63.o -r librpc/gen_ndr/ndr_server_id.c.40.o librpc/gen_ndr/ndr_dfs.c.10.o librpc/gen_ndr/ndr_eventlog.c.62.o librpc/ndr/ndr_spoolss_buf.c.23.o librpc/gen_ndr/ndr_winreg.c.11.o librpc/gen_ndr/ndr_ntsvcs.c.64.o librpc/gen_ndr/ndr_notify.c.47.o librpc/ndr/ndr_netlogon.c.61.o librpc/ndr-standard.empty.c.109.o librpc/gen_ndr/ndr_srvsvc.c.60.o librpc/gen_ndr/ndr_samr.c.53.o librpc/gen_ndr/ndr_lsa.c.54.o librpc/ndr/ndr_svcctl.c.59.o librpc/gen_ndr/ndr_initshutdown.c.67.o librpc/gen_ndr/ndr_svcctl.c.59.o librpc/gen_ndr/ndr_eventlog6.c.63.o librpc/gen_ndr/ndr_atsvc.c.5.o librpc/gen_ndr/ndr_netlogon.c.61.o librpc/gen_ndr/ndr_file_id.c.150.o librpc/gen_ndr/ndr_spoolss.c.22.o librpc/gen_ndr/ndr_wkssvc.c.65.o librpc/gen_ndr/ndr_echo.c.66.o librpc/gen_ndr/ndr_dssetup.c.28.o
cp lib/util/asn1.c.64.o objs/
ld -o objs/loadparm.c.8.o -r lib/param/param_table.c.8.o lib/param/util.c.8.o lib/crypto/gnutls_weak_crypto.c.1.o lib/crypto/gnutls_error.c.1.o lib/param/loadparm.c.8.o lib/crypto/gnutls_arcfour_confounded_md5.c.1.o
ld -o objs/dbwrap.c.1.o -r lib/dbwrap/dbwrap_local_open.c.1.o lib/dbwrap/dbwrap.c.1.o lib/dbwrap/dbwrap_util.c.1.o lib/dbwrap/dbwrap_rbt.c.1.o lib/dbwrap/dbwrap_tdb.c.1.o
ld -o objs/ndr_krb5pac.c.97.o -r librpc/ndr/ndr_krb5pac.c.97.o librpc/gen_ndr/ndr_krb5pac.c.97.o
cp lib/util/msghdr.c.26.o objs/
cp lib/socket/interfaces.c.1.o objs/
cp source4/lib/events/tevent_s4.c.1.o objs/
ld -o objs/ndr_schannel.c.134.o -r lib/compression/lzxpress.c.1.o librpc/gen_ndr/ndr_ntlmssp.c.48.o librpc/gen_ndr/ndr_smb2_lease_struct.c.130.o librpc/ndr/ndr_witness.c.70.o librpc/ndr/ndr_xattr.c.129.o librpc/gen_ndr/ndr_fsrvp.c.69.o librpc/gen_ndr/ndr_epmapper.c.26.o librpc/gen_ndr/ndr_witness.c.70.o librpc/gen_ndr/ndr_orpc.c.31.o librpc/gen_ndr/ndr_dcom.c.34.o librpc/gen_ndr/ndr_mdssvc.c.72.o librpc/ndr/ndr_ntlmssp.c.48.o librpc/ndr/ndr_drsblobs.c.87.o librpc/gen_ndr/ndr_krb5ccache.c.107.o librpc/gen_ndr/ndr_xattr.c.129.o librpc/ndr/ndr_auth.c.2.o librpc/ndr/ndr_compression.c.68.o librpc/gen_ndr/ndr_auth.c.2.o source3/librpc/gen_ndr/ndr_open_files.c.4.o librpc/ndr/ndr_negoex.c.49.o source3/librpc/gen_ndr/ndr_smbXsrv.c.5.o librpc/gen_ndr/ndr_ntprinting.c.52.o librpc/ndr/ndr_dnsserver.c.7.o librpc/gen_ndr/ndr_drsblobs.c.87.o librpc/gen_ndr/ndr_drsuapi.c.80.o librpc/ndr-samba.empty.c.189.o librpc/gen_ndr/ndr_named_pipe_auth.c.6.o librpc/ndr/ndr_drsuapi.c.80.o librpc/gen_ndr/ndr_dnsserver.c.7.o librpc/ndr/ndr_schannel.c.134.o librpc/gen_ndr/ndr_negoex.c.49.o librpc/ndr/ndr_ntprinting.c.52.o librpc/gen_ndr/ndr_idmap.c.46.o librpc/gen_ndr/ndr_mgmt.c.30.o librpc/ndr/ndr_orpc.c.31.o librpc/gen_ndr/ndr_schannel.c.134.o librpc/gen_ndr/ndr_unixinfo.c.21.o
ld -o objs/ldb.c.27.o -r lib/ldb/common/ldb_pack.c.1.o lib/ldb/common/ldb.c.27.o lib/ldb/ldb_map/ldb_map.c.1.o lib/ldb/common/ldb_options.c.1.o lib/ldb/common/ldb_controls.c.1.o lib/ldb/ldb_map/ldb_map_inbound.c.1.o lib/ldb/ldb_map/ldb_map_outbound.c.1.o lib/ldb/common/qsort.c.1.o lib/ldb/common/ldb_dn.c.1.o lib/ldb/common/ldb_utf8.c.1.o lib/ldb/common/ldb_msg.c.1.o lib/ldb/common/ldb_ldif.c.1.o lib/ldb/common/ldb_debug.c.1.o lib/ldb/common/ldb_match.c.1.o lib/ldb/common/attrib_handlers.c.1.o lib/ldb/common/ldb_parse.c.1.o lib/ldb/common/ldb_attributes.c.1.o lib/ldb/common/ldb_modules.c.1.o
ld -o objs/krb5_samba.c.1.o -r lib/krb5_wrap/enctype_convert.c.1.o lib/krb5_wrap/keytab_util.c.1.o lib/krb5_wrap/gss_samba.c.1.o lib/krb5_wrap/krb5_errs.c.1.o lib/krb5_wrap/krb5_samba.c.1.o
ld -o objs/messages_dgm.c.1.o -r lib/messaging/messages_dgm_ref.c.1.o lib/pthreadpool/pthreadpool_tevent.c.1.o lib/pthreadpool/pthreadpool_pipe.c.1.o lib/pthreadpool/pthreadpool.c.1.o lib/messaging/messages_dgm.c.1.o
cp lib/util/server_id_db.c.85.o objs/
cp source3/lib/messages_util.c.38.o objs/
ld -o objs/cluster.c.1.o -r source4/cluster/cluster.c.1.o source4/cluster/local.c.1.o
ld -o objs/tsocket.c.1.o -r lib/tsocket/tsocket_bsd.c.1.o source4/lib/socket/socket_ip.c.4.o source4/lib/socket/connect.c.6.o source4/libcli/resolve/resolve.c.10.o source4/lib/socket/socket.c.6.o source4/lib/socket/connect_multi.c.6.o lib/tsocket/tsocket_helpers.c.1.o lib/util/access.c.87.o source4/lib/socket/socket_unix.c.5.o lib/samba-sockets.empty.c.2.o source4/libcli/composite/composite.c.4.o source4/lib/socket/access.c.6.o lib/tsocket/tsocket.c.1.o
ld -o objs/unix_privs.c.66.o -r source4/lib/messaging/messaging_send.c.1.o lib/util/unix_privs.c.66.o
ld -o objs/ldap_message.c.1.o -r libcli/ldap/ldap_ndr.c.1.o libcli/ldap/ldap_message.c.1.o
ld -o objs/util_str_escape.c.88.o -r libcli/lsarpc/util_lsarpc.c.1.o libcli/auth/smbdes.c.6.o libcli/auth/spnego_parse.c.12.o libcli/auth/credentials.c.6.o libcli/auth/msrpc_parse.c.4.o libcli/auth/schannel_state_tdb.c.9.o libcli/auth/pam_errors.c.11.o lib/util/util_str_escape.c.88.o libcli/auth/smbencrypt.c.6.o libcli/auth/cliauth.empty.c.2.o libcli/auth/session.c.6.o libcli/auth/ntlm_check.c.5.o
cp libds/common/flag_mapping.c.1.o objs/
ld -o objs/audit_logging.c.1.o -r auth/auth_sam_reply.c.1.o auth/auth_util.c.1.o lib/audit_logging/audit_logging.c.1.o auth/auth_log.c.1.o auth/wbc_auth_util.c.1.o
ld -o objs/util.c.6.o -r lib/util/util_runcmd.c.83.o source4/dsdb/common/rodc_helper.c.6.o lib/util/util_ldb.c.80.o source4/dsdb/common/util.c.6.o source4/dsdb/common/util_trusts.c.6.o source4/dsdb/common/dsdb_access.c.6.o source4/dsdb/common/dsdb_dn.c.6.o source4/dsdb/common/util_samr.c.6.o source4/dsdb/common/util_groups.c.6.o source4/dsdb/common/util_links.c.6.o
ld -o objs/ldb_wrap.c.4.o -r source4/dsdb/schema/schema_set.c.9.o source4/dsdb/schema/dsdb_dn.c.9.o lib/ldb-samba/ldif_handlers.c.1.o source4/dsdb/schema/schema_description.c.9.o source4/dsdb/schema/schema_info_attr.c.9.o source4/dsdb/schema/schema_inferiors.c.9.o source4/dsdb/schema/schema_init.c.9.o source4/dsdb/schema/schema_convert_to_ol.c.9.o source4/dsdb/schema/schema_query.c.9.o source4/dsdb/schema/schema_prefixmap.c.9.o lib/ldb-samba/ldb_wrap.c.4.o source4/dsdb/schema/schema_syntax.c.9.o source4/dsdb/schema/schema_filtered.c.9.o lib/ldb-samba/ldb_matching_rules.c.1.o
ld -o objs/kerberos_pac.c.2.o -r source4/auth/kerberos/krb5_init_context.c.1.o auth/kerberos/gssapi_pac.c.1.o source4/auth/kerberos/kerberos_pac.c.2.o auth/kerberos/gssapi_helper.c.1.o source4/lib/stream/packet.c.1.o auth/kerberos/kerberos_pac.c.1.o source4/lib/tls/tls_tstream.c.1.o source4/lib/tls/tlscert.c.1.o
ld -o objs/credentials_ntlm.c.9.o -r auth/credentials/credentials.c.1.o source4/auth/kerberos/kerberos_util.c.5.o auth/credentials/credentials_secrets.c.8.o source4/auth/kerberos/srv_keytab.c.7.o auth/credentials/credentials_krb5.c.7.o source4/param/secrets.c.5.o auth/credentials/credentials_ntlm.c.9.o
ld -o objs/wb_common.c.2.o -r nsswitch/wb_common.c.2.o lib/replace/closefrom.c.2.o lib/util/smb_strtox.c.23.o nsswitch/libwbclient/wbc_pam.c.4.o nsswitch/libwbclient/wbc_pwd.c.4.o nsswitch/libwbclient/wbc_guid.c.4.o lib/replace/replace.c.2.o nsswitch/libwbclient/wbc_idmap.c.4.o nsswitch/libwbclient/wbc_util.c.4.o nsswitch/libwbclient/wbclient.c.4.o nsswitch/libwbclient/wbc_sid.c.4.o
ld -o objs/session.c.1.o -r source4/dsdb/repl/replicated_objects.c.1.o source4/auth/system_session.c.9.o source4/dsdb/samdb/samdb.c.1.o source4/dsdb/samdb/samdb_privilege.c.1.o source4/auth/session.c.1.o source4/auth/sam.c.11.o source4/dsdb/samdb/cracknames.c.1.o libcli/drsuapi/repl_decrypt.c.1.o
cp lib/util/modules.c.62.o objs/
ld -o objs/util_sec.c.89.o -r source3/lib/util_str.c.89.o source3/lib/file_id.c.89.o source3/lib/cbuf.c.89.o source3/lib/util_malloc.c.89.o source3/lib/adt_tree.c.89.o source3/lib/util_sec.c.89.o source3/lib/namearray.c.89.o source3/lib/per_thread_cwd.c.89.o
ld -o objs/dns.c.1.o -r libcli/dns/dns.c.1.o libcli/dns/resolvconf.c.1.o
ld -o objs/gensec_tstream.c.1.o -r auth/gensec/gensec_util.c.1.o auth/gensec/gensec.c.1.o source4/auth/gensec/gensec_tstream.c.1.o auth/ntlmssp/gensec_ntlmssp.c.1.o auth/ntlmssp/gensec_ntlmssp_server.c.1.o libcli/http/gensec/basic.c.3.o auth/gensec/spnego.c.4.o auth/ntlmssp/ntlmssp_sign.c.1.o auth/gensec/external.c.7.o auth/ntlmssp/gensec_ntlmssp.empty.c.3.o auth/gensec/schannel.c.5.o libcli/http/gensec/generic.c.4.o auth/gensec/gensec_start.c.1.o auth/gensec/ncalrpc.c.6.o auth/ntlmssp/ntlmssp_server.c.1.o source4/auth/gensec/gensec_gssapi.c.3.o auth/ntlmssp/ntlmssp_ndr.c.1.o auth/ntlmssp/ntlmssp.c.1.o auth/ntlmssp/ntlmssp_util.c.1.o auth/ntlmssp/ntlmssp_client.c.1.o
cp lib/util/talloc_report_printf.c.18.o objs/
cp libcli/registry/util_reg.c.1.o objs/
ld -o objs/cluster_support.c.35.o -r source3/lib/cluster_support.c.35.o source3/lib/ctdb_dummy.c.35.o
cp source3/lib/smbd_shim.c.41.o objs/
ld -o objs/charcnv.c.93.o -r source3/lib/charcnv.c.93.o source3/lib/fstring.c.93.o
cp source4/lib/socket/interface.c.1.o objs/
ld -o objs/lmhosts.c.3.o -r libcli/nbt/namerefresh.c.4.o libcli/nbt/nbtsocket.c.4.o libcli/nbt/lmhosts.c.3.o libcli/nbt/namerelease.c.4.o libcli/nbt/namequery.c.4.o libcli/nbt/nameregister.c.4.o
ld -o objs/dnsquery.c.1.o -r lib/addns/dnsmarshall.c.1.o lib/addns/dnsutils.c.1.o lib/addns/dnsquery.c.1.o lib/addns/dnsgss.c.1.o lib/addns/error.c.1.o lib/addns/dnsrecord.c.1.o libcli/dns/dns_lookup.c.3.o lib/addns/dnssock.c.1.o lib/addns/dnsquery_srv.c.1.o
ld -o objs/loadparm.c.53.o -r source3/lib/util_tdb.c.88.o source3/lib/smbrun.c.40.o source3/registry/reg_backend_db.c.27.o source3/lib/substitute.c.40.o source3/lib/util_macstreams.c.34.o lib/util/debug_s3.c.40.o source3/lib/util.c.34.o source3/lib/util_nttoken.c.27.o source3/libsmb/smberr.c.95.o source3/lib/ldap_escape.c.40.o source3/lib/util_specialsids.c.34.o source3/libsmb/errormap.c.95.o source3/lib/background.c.40.o source3/lib/util_cluster.c.40.o source3/lib/namemap_cache.c.40.o lib/smbconf/smbconf.c.1.o source3/lib/idmap_cache.c.40.o lib/async_req/async_sock.c.1.o source3/registry/reg_cachehook.c.27.o source3/lib/util_tsock.c.34.o source3/lib/serverid.c.40.o source3/lib/util_path.c.34.o source3/lib/messages.c.40.o source3/lib/smbconf/smbconf_init.c.54.o librpc/gen_ndr/ndr_messaging.c.151.o source3/lib/util_names.c.53.o source3/lib/util_transfer_file.c.34.o source3/registry/reg_api_util.c.28.o source3/lib/dumpcore.c.40.o source3/lib/util_file.c.34.o source3/registry/reg_util_internal.c.27.o source3/registry/reg_backend_smbconf.c.28.o source3/lib/util_sid.c.34.o source3/param/loadparm.c.53.o source3/registry/reg_parse.c.27.o source3/lib/dmallocmsg.c.40.o lib/smbconf/smbconf_txt.c.1.o source3/lib/substitute_generic.c.40.o source3/lib/util_sock.c.34.o source3/lib/time.c.34.o source3/lib/server_id_watch.c.40.o source3/lib/system.c.34.o source3/lib/sendfile.c.34.o source3/lib/ldap_debug_handler.c.53.o source3/lib/global_contexts.c.40.o source3/registry/reg_dispatcher.c.27.o lib/util/util_pw.c.84.o source3/lib/interface.c.40.o source3/lib/ms_fnmatch.c.40.o source3/lib/gencache.c.40.o lib/smbconf/smbconf_util.c.1.o source3/lib/username.c.40.o source3/lib/system_smbd.c.40.o source3/lib/dbwrap/dbwrap_open.c.37.o source3/lib/recvfile.c.34.o source3/lib/g_lock.c.37.o source3/lib/errmap_unix.c.95.o source3/registry/reg_init_basic.c.27.o source3/lib/srprs.c.27.o source3/lib/tallocmsg.c.40.o source3/lib/util_matching.c.34.o source3/lib/util_event.c.40.o source3/param/util.c.1.o source3/lib/util_procid.c.34.o source3/registry/reg_util_token.c.28.o source3/lib/version.c.82.o source3/lib/id_cache.c.40.o source3/lib/util_ea.c.40.o source3/lib/sharesec.c.53.o source3/registry/reg_init_smbconf.c.28.o source3/param/loadparm_ctx.c.2.o source3/lib/addrchange.c.40.o source3/registry/reg_objects.c.27.o source3/registry/reg_api.c.27.o source3/lib/smbconf/smbconf_reg.c.54.o source3/lib/audit.c.40.o source3/registry/reg_parse_internal.c.27.o source3/lib/server_id_db_util.c.40.o source3/lib/dbwrap/dbwrap_watch.c.37.o source3/lib/wins_srv.c.40.o
ld -o objs/bcast.c.12.o -r source4/libcli/ldap/ldap_ildap.c.1.o source4/libcli/ldap/ldap_bind.c.1.o source4/libcli/ldap/ldap_client.c.1.o source4/libcli/resolve/dns_ex.c.12.o source4/libcli/resolve/lmhosts.c.12.o source4/libcli/ldap/ldap_controls.c.1.o source4/libcli/resolve/wins.c.12.o source4/libcli/resolve/resolve_lp.c.12.o source4/libcli/resolve/host.c.12.o source4/libcli/resolve/nbtlist.c.12.o source4/libcli/resolve/bcast.c.12.o libcli/util/tstream.c.1.o
ld -o objs/cldap.c.1.o -r libcli/cldap/cldap.c.1.o libcli/netlogon/netlogon.c.1.o
ld -o objs/async_sock.c.1.o -r libcli/smb/read_smb.c.1.o
ld -o objs/ndr_secrets.c.7.o -r source3/passdb/machine_account_secrets.c.47.o source3/librpc/gen_ndr/ndr_secrets.c.7.o source3/passdb/machine_sid.c.47.o source3/passdb/secrets_lsa.c.47.o source3/passdb/secrets.c.47.o
ld -o objs/smb_signing.c.3.o -r libcli/smb/smb1cli_create.c.3.o libcli/smb/smb1cli_write.c.3.o libcli/smb/smb2cli_write.c.3.o libcli/smb/smb_signing.c.3.o libcli/smb/smb1cli_trans.c.3.o libcli/smb/smb2cli_query_directory.c.3.o libcli/smb/smb1cli_read.c.3.o libcli/smb/smb2cli_ioctl.c.3.o libcli/smb/util.c.3.o libcli/smb/smb2cli_set_info.c.3.o libcli/smb/reparse_symlink.c.3.o libcli/smb/smb2cli_query_info.c.3.o libcli/smb/smb2cli_create.c.3.o libcli/smb/smbXcli_base.c.3.o libcli/smb/smb1cli_session.c.3.o libcli/smb/smb2cli_read.c.3.o libcli/smb/smb2_create_blob.c.3.o libcli/smb/smb_seal.c.3.o libcli/smb/smb2_negotiate_context.c.3.o libcli/smb/smb1cli_close.c.3.o libcli/smb/tstream_smbXcli_np.c.3.o libcli/smb/smb2cli_close.c.3.o libcli/smb/smb2_lease.c.3.o libcli/smb/smb2_signing.c.3.o libcli/smb/smb2cli_session.c.3.o libcli/smb/smb2cli_tcon.c.3.o libcli/smb/smb2cli_echo.c.3.o libcli/smb/smb2_posix.c.3.o libcli/smb/smb2cli_notify.c.3.o libcli/smb/smb1cli_echo.c.3.o libcli/smb/smb2cli_flush.c.3.o
ld -o objs/dcerpc_error.c.206.o -r librpc/ndr/ndr_dcerpc.c.73.o librpc/rpc/binding.c.206.o librpc/gen_ndr/ndr_dcerpc.c.73.o librpc/rpc/binding_handle.c.206.o librpc/rpc/dcerpc_util.c.206.o librpc/rpc/dcerpc_error.c.206.o
ld -o objs/unexpected.c.78.o -r source3/libads/cldap.c.46.o source3/libsmb/namecache.c.78.o source3/libsmb/nmblib.c.78.o source3/libads/kerberos.c.33.o source3/libsmb/conncache.c.78.o source3/libsmb/namequery.c.78.o source3/libsmb/unexpected.c.78.o source3/libads/sitename_cache.c.78.o source3/libsmb/clidgram.c.78.o source3/librpc/crypto/gse_krb5.c.8.o source3/libads/ads_status.c.33.o source3/librpc/crypto/gse.c.8.o
ld -o objs/popt.c.1.o -r third_party/popt/popthelp.c.1.o third_party/popt/poptconfig.c.1.o third_party/popt/poptparse.c.1.o third_party/popt/poptint.c.1.o third_party/popt/popt.c.1.o
ld -o objs/dcerpc-samba.empty.c.192.o -r librpc/gen_ndr/ndr_srvsvc_c.c.165.o librpc/dcerpc-samba.empty.c.192.o librpc/gen_ndr/ndr_initshutdown_c.c.175.o librpc/gen_ndr/ndr_eventlog_c.c.171.o librpc/gen_ndr/ndr_svcctl_c.c.166.o librpc/gen_ndr/ndr_dnsserver_c.c.182.o librpc/gen_ndr/ndr_epmapper_c.c.172.o librpc/gen_ndr/ndr_atsvc_c.c.153.o librpc/gen_ndr/ndr_lsa_c.c.155.o librpc/gen_ndr/ndr_samr_c.c.156.o librpc/gen_ndr/ndr_echo_c.c.154.o librpc/gen_ndr/ndr_ntsvcs_c.c.179.o librpc/gen_ndr/ndr_dfs_c.c.157.o librpc/gen_ndr/ndr_spoolss_c.c.162.o librpc/gen_ndr/ndr_wkssvc_c.c.164.o librpc/gen_ndr/ndr_winreg_c.c.174.o librpc/gen_ndr/ndr_netlogon_c.c.180.o
ld -o objs/npa_tstream.c.1.o -r libcli/named_pipe_auth/tstream_u32_read.c.1.o libcli/named_pipe_auth/npa_tstream.c.1.o
ld -o objs/clientgen.c.44.o -r librpc/gen_ndr/ndr_ioctl.c.183.o source3/libsmb/clisecdesc.c.44.o source3/libsmb/async_smb.c.44.o source3/libsmb/clifsinfo.c.44.o source3/libsmb/clistr.c.44.o source3/libsmb/cliconnect.c.44.o librpc/ndr/ndr_ioctl.c.183.o source3/libsmb/clitrans.c.44.o source3/libsmb/clientgen.c.44.o source3/libsmb/clispnego.c.44.o source3/libsmb/cliprint.c.44.o source3/libsmb/smbsock_connect.c.44.o source3/libsmb/clilist.c.44.o source3/libsmb/climessage.c.44.o source3/libsmb/clidfs.c.44.o source3/libsmb/auth_generic.c.43.o source3/libsmb/clioplock.c.44.o source3/libsmb/clisymlink.c.44.o source3/libsmb/clifile.c.44.o source3/libsmb/clierror.c.44.o source3/libsmb/clireadwrite.c.44.o source3/libsmb/clirap.c.44.o source3/libsmb/cliquota.c.44.o librpc/gen_ndr/ndr_quota.c.133.o source3/libsmb/cli_smb2_fnum.c.44.o
ld -o objs/ndr_table.c.14.o -r librpc/ndr/ndr_rap.c.45.o librpc/gen_ndr/ndr_dsbackup.c.9.o librpc/ndr/ndr_backupkey.c.147.o librpc/gen_ndr/ndr_frsapi.c.15.o librpc/gen_ndr/ndr_audiosrv.c.1.o librpc/gen_ndr/ndr_browser.c.37.o librpc/gen_ndr/ndr_rap.c.45.o librpc/gen_ndr/ndr_rot.c.13.o source4/librpc/gen_ndr/ndr_winsrepl.c.6.o librpc/gen_ndr/ndr_frsrpc.c.14.o librpc/gen_ndr/ndr_fscc.c.19.o librpc/gen_ndr/ndr_wzcsvc.c.36.o librpc/gen_ndr/ndr_scerpc.c.39.o source4/librpc/gen_ndr/ndr_irpc.c.1.o librpc/ndr/ndr_frsrpc.c.14.o librpc/gen_ndr/ndr_winstation.c.152.o librpc/ndr/ndr_table.c.14.o source4/librpc/gen_ndr/ndr_ntp_signd.c.5.o librpc/gen_ndr/ndr_msgsvc.c.29.o librpc/gen_ndr/ndr_keysvc.c.44.o librpc/ndr/ndr_ODJ.c.94.o librpc/gen_ndr/ndr_w32time.c.38.o librpc/gen_ndr/ndr_trkwks.c.43.o librpc/ndr/ndr_bkupblobs.c.18.o librpc/gen_ndr/ndr_policyagent.c.20.o source4/librpc/ndr-samba4.empty.c.8.o source3/librpc/gen_ndr/ndr_leases_db.c.6.o librpc/gen_ndr/ndr_printcap.c.25.o librpc/gen_ndr/ndr_cab.c.149.o source4/librpc/gen_ndr/tables.c.14.o librpc/ndr/ndr_wmi.c.35.o source4/librpc/gen_ndr/ndr_sasl_helpers.c.2.o librpc/gen_ndr/ndr_ODJ.c.94.o librpc/gen_ndr/ndr_dfsblobs.c.17.o source4/librpc/gen_ndr/ndr_winsif.c.3.o librpc/gen_ndr/ndr_winbind.c.218.o librpc/gen_ndr/ndr_winspool.c.24.o librpc/gen_ndr/ndr_preg.c.148.o source4/librpc/gen_ndr/ndr_opendb.c.4.o librpc/gen_ndr/ndr_frstrans.c.16.o librpc/gen_ndr/ndr_smb_acl.c.58.o librpc/gen_ndr/ndr_nfs4acl.c.51.o librpc/ndr/ndr_preg.c.148.o librpc/gen_ndr/ndr_remact.c.33.o librpc/gen_ndr/ndr_dbgidl.c.27.o librpc/gen_ndr/ndr_efs.c.12.o librpc/gen_ndr/ndr_wmi.c.35.o librpc/ndr/ndr_cab.c.149.o librpc/gen_ndr/ndr_oxidresolver.c.32.o librpc/gen_ndr/ndr_fsrvp_state.c.220.o source3/librpc/gen_ndr/ndr_perfcount.c.8.o librpc/gen_ndr/ndr_backupkey.c.147.o librpc/gen_ndr/ndr_clusapi.c.71.o librpc/gen_ndr/ndr_bkupblobs.c.18.o
ld -o objs/cmdline.c.1.o -r lib/cmdline/cmdline.c.1.o auth/credentials/credentials_cmdline.c.10.o lib/cmdline/closefrom_except.c.1.o
ld -o objs/cli_pipe.c.10.o -r libcli/auth/netlogon_creds_cli.c.10.o source3/rpc_client/rpc_transport_tstream.c.10.o source3/rpc_client/cli_pipe.c.10.o source3/rpc_client/local_np.c.10.o source3/rpc_client/rpc_transport_sock.c.10.o source3/rpc_client/rpc_transport_np.c.10.o source3/librpc/rpc/dcerpc_helpers.c.10.o
/TASE/bin/clang -mno-mmx -mno-sse -mno-sse2 -mno-sse3 -mno-sse4 -mno-80387 -mno-avx -mllvm -x86-tase-modeled-functions=/TASE/include/tase/core_modeled.h -c /harness.c -o /harness.o
ld -o objs/harness.o -r source3/client/client.c.116.o lib/cmdline/cmdline_s3.c.3.o libcli/smbreadline/smbreadline.c.1.o source3/client/dnsbrowse.c.116.o /harness.o source3/client/clitar.c.116.o
cd objs/
for x in $(ls); do objcopy --localize-hidden $x; done
ld -r $(ls) /TASE/lib/musl.o -o everything.o
cd /TASE/install/ && ./localize.sh /samba/bin/default/objs/everything.o
mv /samba/bin/default/objs/everything.o /samba/bin/default/source3/client/
cd /samba/bin/default/source3/client/
/usr/bin/c++ -T/TASE/tase_link.ld -fno-pie -no-pie -D_GLIBCXX_USE_CXX11_ABI=0 -I/TASE/include/openssl/ -Wall -Wextra -Wno-unused-parameter -O0 -o/samba/bin/default/source3/client/smbclient -rdynamic /TASE/lib/main.cpp.o everything.o -L/usr/lib/x86_64-linux-gnu/mit-krb5 -Wl,--start-group /TASE/lib/libtase.a /TASE/lib/libkleeCore.a /TASE/lib/libkleeModule.a /TASE/lib/libkleeTase.a /TASE/lib/libkleeCore.a /TASE/lib/libkleeModule.a /TASE/lib/libkleeTase.a /TASE/lib/libkleeBasic.a /TASE/lib/libkleaverSolver.a /TASE/lib/libkleeBasic.a /TASE/lib/libkleaverSolver.a /TASE/lib/libstp.a /TASE/lib/libminisat.a /TASE/lib/libkleaverExpr.a /TASE/lib/libkleeSupport.a /TASE/llvm-3.4.2/lib/libLLVMInstrumentation.a /TASE/llvm-3.4.2/lib/libLLVMIRReader.a /TASE/llvm-3.4.2/lib/libLLVMAsmParser.a /TASE/llvm-3.4.2/lib/libLLVMOption.a /TASE/llvm-3.4.2/lib/libLLVMLTO.a /TASE/llvm-3.4.2/lib/libLLVMLinker.a /TASE/llvm-3.4.2/lib/libLLVMipo.a /TASE/llvm-3.4.2/lib/libLLVMVectorize.a /TASE/llvm-3.4.2/lib/libLLVMTableGen.a /TASE/llvm-3.4.2/lib/libLLVMX86Disassembler.a /TASE/llvm-3.4.2/lib/libLLVMX86AsmParser.a /TASE/llvm-3.4.2/lib/libLLVMX86CodeGen.a /TASE/llvm-3.4.2/lib/libLLVMSelectionDAG.a /TASE/llvm-3.4.2/lib/libLLVMAsmPrinter.a /TASE/llvm-3.4.2/lib/libLLVMMCDisassembler.a /TASE/llvm-3.4.2/lib/libLLVMMCParser.a /TASE/llvm-3.4.2/lib/libLLVMX86Desc.a /TASE/llvm-3.4.2/lib/libLLVMX86Info.a /TASE/llvm-3.4.2/lib/libLLVMX86AsmPrinter.a /TASE/llvm-3.4.2/lib/libLLVMX86Utils.a /TASE/llvm-3.4.2/lib/libLLVMInterpreter.a /TASE/llvm-3.4.2/lib/libLLVMMCJIT.a /TASE/llvm-3.4.2/lib/libLLVMRuntimeDyld.a /TASE/llvm-3.4.2/lib/libLLVMExecutionEngine.a /TASE/llvm-3.4.2/lib/libLLVMCodeGen.a /TASE/llvm-3.4.2/lib/libLLVMObjCARCOpts.a /TASE/llvm-3.4.2/lib/libLLVMScalarOpts.a /TASE/llvm-3.4.2/lib/libLLVMInstCombine.a /TASE/llvm-3.4.2/lib/libLLVMTransformUtils.a /TASE/llvm-3.4.2/lib/libLLVMAnalysis.a /TASE/llvm-3.4.2/lib/libLLVMTarget.a /TASE/llvm-3.4.2/lib/libLLVMMC.a /TASE/llvm-3.4.2/lib/libLLVMObject.a /TASE/llvm-3.4.2/lib/libLLVMBitWriter.a /TASE/llvm-3.4.2/lib/libLLVMBitReader.a /TASE/llvm-3.4.2/lib/libLLVMCore.a /TASE/llvm-3.4.2/lib/libLLVMSupport.a /TASE/llvm-3.4.2/lib/libLLVMJIT.a /TASE/llvm-3.4.2/lib/libLTO.a /TASE/llvm-3.4.2/lib/libLLVMipa.a -lz -lpthread -ltinfo -ldl -lm -lstdc++ -lgnutls -lkrb5 -lk5crypto -lcom_err -lgssapi_krb5 -lcap -lresolv -Wl,--end-group
echo "#!/bin/bash" > run_smbclient.sh
echo 'KLEE_RUNTIME_LIBRARY_PATH=/samba/bin/default/source3/client/build/bitcode/ ./smbclient "${@}"' >> run_smbclient.sh
chmod +x run_smbclient.sh
mkdir -p build/bitcode
cp /TASE/install/libtasec.syms client.tase.tmp
for x in $(ls /samba/bin/default/objs/); do  python3 /TASE/parseltongue86/rosettastone.py smbclient -f /samba/bin/default/objs/$x >> client.vars.tmp; nm --defined-only /samba/bin/default/objs/$x | grep -i " t " | cut -d' ' -f 3 >> client.tase.tmp; done
sort client.tase.tmp | uniq > client.tase && rm client.tase.tmp
sort client.vars.tmp | uniq > client.vars && rm client.vars.tmp
cp /TASE/install/klee_bitcode/* build/bitcode
./run_smbclient.sh -tasePreProcess=TRUE
python3 /TASE/parseltongue86/parseltongue86.py -f client.tase smbclient /TASE/include/tase/ client -t 20
echo '#!/bin/bash' > compile.sh
echo '/TASE/llvm-3.4.2/bin/clang -fno-slp-vectorize -Wall -Wextra -emit-llvm -Wno-unused -O3 -std=c++11 -c $1 -o build/bitcode/$(basename -s .cpp $1).bc' >> compile.sh
chmod +x compile.sh
ls build/bitcode | grep .cpp$ | xargs -n1 -P20 -I{} ./compile.sh build/bitcode/{}
if [[ $(ls build/bitcode | grep -E -c 'client.interp.[0-9]+.bc$') -gt 1 ]]
then
    /TASE/llvm-3.4.2/bin/llvm-link build/bitcode/client.interp.*.bc -o build/bitcode/client.interp.bc
else
    mv build/bitcode/client.interp.0.bc build/bitcode/client.interp.bc
fi

objdump -D -C -w -M suffix -j .text smbclient > obj.dump

./run_smbclient.sh -taseManager=false -dontFork -execMode=INTERP_ONLY -taseDebug -modelDebug - --help
